- name: Remove KICS
  file:
    state: absent
    path: "{{ lookup('env', 'HOME') }}/opt/kics"
  tags:
    - kics

- name: Clone KICS
  git:
    repo: 'https://github.com/Checkmarx/kics.git'
    dest: "{{ lookup('env', 'HOME') }}/opt/kics"
  tags:
    - kics

- name: Build KICS
  shell: "cd {{ lookup('env', 'HOME') }}/opt/kics && make build"
  register: build_output
  changed_when: build_output.rc != 0
  tags:
    - kics

- name: Install KICS
  become: true
  copy:
    src: "{{ lookup('env', 'HOME') }}/opt/kics/bin/kics"
    dest: /usr/local/bin/kics
    mode: 'u+x,g+x'
    group: users
  tags:
    - kics
