- name: Install shell requirements for Linux
  become: true
  package:
    name:
      - "{{ item }}"
    state: present
  with_items: "{{ shell_packages }}"
  tags:
    - shell

- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  register: build_output
  changed_when: build_output.rc != 0
  tags:
    - shell
