repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ccecdbda02e324779f1e18ae245c07ee923a8bae
    hooks:
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-yaml
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v5.3.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: tflint
        args:
          - "--module"
          - "--config=.tflint.hcl"
      - id: terraform-validate
      - id: terraform-fmt
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_tfsec
      - id: terraform_docs
      - id: checkov
