#!/usr/bin/env bash

## install i3 wm and some other related tools
sudo pacman -S i3 i3-gaps i3status i3lock dmenu arandr xorg picom \
               lxappearance pcmanfm xfce4-terminal feh imagemagick \
               picom thunar

## install fonts and themes
sudo pacman -S ttf-dejavu ttf-liberation noto-fonts lightdm lightdm-gtk-greeter \
               lightdm-gtk-greeter-settings materia-gtk-theme papirus-icon-theme

## Copy font-awesome ttfs for icons
mv ~/.fonts ~/.dotfiles/original_backup/.fonts
ln -s ~/.dotfiles/fonts ~/.fonts

## Copy i3 config files
mv ~/.config/i3 ~/.dotfiles/original_backup/i3
ln -s ~/.dotfiles/i3 ~/.config/i3

## Successful exit
exit 0
