#!/usr/bin/env bash

declare -a exclusion=(install original_backup vim)

#git clone --recursive git://github.com/cello1500/dotfiles.git
#git submodule update --init --recursive "${DOTBOT_DIR}"

in_array() {
    local haystack=${1}[@]
    local needle=${2}
    for i in ${!haystack}; do
        if [[ ${i} == ${needle} ]]; then
            return 0
        fi
    done
    return 1
}

shopt -s nullglob

for f in ~/.dotfiles/*
do
	filename=${f##*/}
	if in_array exclusion $filename; then
		continue
	fi
	if [ -e ~/.$filename ] && [ ! -L ~/.$filename ]; then
		mkdir -p ~/.dotfiles/original
		mv ~/.$filename ~/.dotfiles/original_backup/
	fi

	ln -fsv $f ~/.$filename
done

# Install latest VIM Pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# install lastest VIM Syntastic
if [ -e ~/.vim/bundle/syntastic ]; then
	rm -rf  ~/.vim/bundle/syntastic
fi
git clone https://github.com/scrooloose/syntastic.git ~/.vim/bundle/syntastic

# Install lastest VIM Sensible
if [ -e  ~/.vim/bundle/vim-sensible ]; then
	rm -rf  ~/.vim/bundle/vim-sensible
fi
git clone git://github.com/tpope/vim-sensible.git ~/.vim/bundle/vim-sensible

# Install lastest VIM vim-go
if [ -e  ~/.vim/bundle/vim-sensible ]; then
	rm -rf  ~/.vim/bundle/vim-go
fi
git clone https://github.com/fatih/vim-go.git ~/.vim/bundle/vim-go

# Install VIM Conque-Term
vim 'https://conque.googlecode.com/files/conque_2.3.vmb' -c ':so % | q'
