#!/usr/bin/env bash

## This scripts needs Golang installed beforehand

## Download source code
git clone https://github.com/hashicorp/terraform.git

## Compile source code and put the binary in the PATH
cd terraform || exit 1
go install

## Clean source code
cd ..
rm -rf terraform

## Enable terraform auto-completion
terraform -install-autocomplete

## Successful exit
exit 0
