#!/usr/bin/env bash

set -x

version=$1

if [[ $version == "" ]]; then
    echo Error: please specify the version number \(e.g. 1.6.2\)
    exit 1
fi

# Installing Go
echo \*\*\* Downloading golang version "$version"
curl https://storage.googleapis.com/golang/go"$version".linux-amd64.tar.gz -o /tmp/golang.tar.gz
echo \*\*\* Installing Golang version "$version"
sudo rm -r /usr/local/go
sudo tar -C /usr/local -xzf /tmp/golang.tar.gz
rm /tmp/golang.tar.gz

# Configure Go development environment
if [[ ! "$PATH" =~ .*\/go\/.* ]]; then
	export GOPATH=~/workspace/go
	export PATH=$PATH:/usr/local/go/bin:${GOPATH//://bin:}/bin
fi
if [ ! -e ~/workspace ]; then
	echo \*\*\* Creating ~/workspace directory structure
	mkdir -p ~/workspace/go/src
	# install all go additional tools
	go get golang.org/x/tools/cmd/...
else
	echo \*\*\* Updating Vendor packages
	go get -u all
fi
