#!/usr/bin/env bash

## Go is a pre-requisite to install kind
## using this method. You can always consult
## the docs for the Linux alternative

## Install kind
GO111MODULE="on" go get sigs.k8s.io/kind@v0.9.0

## Restart the host after the installation to
## get the correct iptables settings in place

## Successful exit
exit 0
