#!/usr/bin/env bash

declare -a exclusion=(i3 install-docker install-env install-golang install-root install-vim install-terraform original_backup README.md)

in_array() {
    local haystack=${1}[@]
    local needle=${2}
    for i in ${!haystack}; do
        if [[ ${i} == ${needle} ]]; then
            return 0
        fi
    done
    return 1
}

shopt -s nullglob

for f in ~/.dotfiles/*
do
	filename=${f##*/}
	if in_array exclusion $filename; then
		continue
	fi
	if [ -e ~/.$filename ] && [ ! -L ~/.$filename ]; then
		mkdir -p ~/.dotfiles/original_backup
		mv ~/.$filename ~/.dotfiles/original_backup/
	fi

	ln -fsv $f ~/.$filename
done

if [[ `uname -r` == *"arch"* ]]; then
	sudo pacman -S --needed --noconfirm python lua curl tmux git bash-completion xorg-xinit dmenu terminator scrot imagemagick feh arandr
  sudo pacman -S i3
  cp -R i3/ ~/.config/i3/
fi

if [ -d "/usr/local/go" ]; then
	export GOPATH=~/workspace/go
	export PATH=$PATH:/usr/local/go/bin:${GOPATH//://bin:}/bin
fi

# create an ssh key in case we don't have it yet
if [ ! -e "~/.ssh/id_rsa" ]; then
	echo -e  'y\n' | ssh-keygen -t rsa -b 4096 -C "ariguille.gp@gmail.com" -q -f ~/.ssh/id_rsa -N "" > /dev/null
fi

# support for git commands completion on bash
curl -o ~/.git-completion.bash  https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash

# check git repo status in your prompt
rm -rf ~/.bash-git-prompt 2> /dev/null
git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1

# install shellcheck -- very useful to audit bash scripts
sudo pacman -S shellcheck

# added jq for json manipulation
sudo pacman -S jq
