#!/usr/bin/env bash

sudo ln -sfv /home/aristides/.dotfiles/bashrc /root/.bashrc
sudo ln -sfv /home/aristides/.git-completion.bash /root/.git-completion.bash
sudo ln -sfv /home/aristides/.bash-git-prompt /root/.bash-git-prompt
sudo ln -sfv /home/aristides/.vim /root/.vim
sudo ln -sfv /home/aristdes/.vimrc /root/.vimrc
