#!/usr/bin/env bash

# Install VIM and needed utils
sudo pacman -S --needed --noconfirm vim python-pip ctags yamllint

## Needed for vim8+ and deoplete
pip3 install pynvim

## Copy yamllint config files
if [ -f "$HOME/.config/yamllint" ]; then
  mv ~/.config/yamllint ~/.dotfiles/original_backup/yamllint
fi
ln -s ~/.dotfiles/yamllint ~/.config/yamllint
exit 0
