#!/usr/bin/env bash

version=$1

if [[ $version == "" ]]; then
	echo Error: please specify the version number \(eq. 1.6.2\)
	exit 1
fi

echo \*\*\* Downloading golang version $1
curl https://storage.googleapis.com/golang/go$version.linux-amd64.tar.gz -o /tmp/golang.tar.gz
echo \*\*\* Installing Golang version $1
sudo rm -R /usr/local/go
sudo tar -C /usr/local -xzf /tmp/golang.tar.gz
rm /tmp/golang.tar.gz

# Configure GO development environment
if [[ ! "$PATH" =~ .*\/go\/.* ]]; then
	export GOPATH=~/code/go
	export PATH=$PATH:/usr/local/go/bin:${GOPATH//://bin:}/bin
fi
if [ ! -e ~/code ]; then
	echo \*\*\* Creating ~/code directory structure
	mkdir -p ~/code/go/src
	# install all go additional tools
	go get golang.org/x/tools/cmd/...
else
	echo \*\*\* Updating Vendor packages
	go get -u all
fi

source install-vim
