#!/usr/bin/env bash

## Do not make soft links out of these file system objects
declare -a exclusion=(install-base install-bpf-tools install-docker install-dockercompose \
                      install-gcloud install-golang install-k8s-tools install-terraform \
                      install-vim install-root install-ssl-tools original_backup README.md)

in_array() {
  local haystack=${1}[@]
  local needle=${2}
  for i in ${!haystack}; do
    if [[ ${i} == ${needle} ]]; then
      return 0
    fi
  done
  return 1
}

shopt -s nullglob

for f in ~/.dotfiles/*; do
	filename=${f##*/}
	if in_array exclusion "$filename"; then
		continue
	fi

	if [ -e ~/."$filename" ] && [ ! -L ~/."$filename" ]; then
		mkdir -p ~/.dotfiles/original_backup
		mv ~/."$filename" ~/.dotfiles/original_backup/
	fi

	ln -fsv "$f" ~/."$filename"
done

## Install packages for setting personalized environment
sudo pacman -S --needed --noconfirm arandr alsa-utils bash-completion curl feh firefox htop \
                                    imagemagick jq lsof ncdu pacman-contrib playerctl p7zip \
                                    rofi rsync shellcheck scrot tar tmux unzip unrar wget zsh

## Audio codecs and tools
sudo pacman -S --needed --noconfirm a52dec faac faad2 flac jasper lame libdca libdv libmad \
                                    libmpeg2 libtheora libvorbis libxv wavpack x264 xvidcore vlc

## Fix audio issues
sudo pacman -S --needed --noconfirm sof-firmware
echo "load-module module-alsa-sink device=hw:0,0 channels=4" >> /etc/pulse/default.pa
echo "load-module module-alsa-source device=hw:0,6 channels=4" >> /etc/pulse/default.pa

## If you have a system-wide PulseAudio setup make sure the user running the daemon (usually pulse)
## is in the lp group and you load the bluetooth modules in your PulseAudio config:
echo "load-module module-bluetooth-policy" >> /etc/pulse/system.pa
echo "load-module module-bluetooth-discover" >> /etc/pulse/system.pa

## Install helper for dealing with AUR packages
git clone https://aur.archlinux.org/yay.git
cd yay || exit 1
makepkg -si
cd .. && rm -rf yay

## Added slack desktop client
yay -S slack-desktop

## Added dos to unix conversion tool
yay -S dos2unix

# create an ssh key in case we don't have it yet
if [ ! -e "$HOME/.ssh/id_rsa" ]; then
	echo -e  'y\n' | ssh-keygen -t rsa -b 4096 -C "ariguille.gp@gmail.com" -q -f ~/.ssh/id_rsa -N "" > /dev/null
fi
