#!/usr/bin/env bash

# Install VIM and needed utils
sudo pacman -S --needed --noconfirm vim python-pip ctags yamllint

# Install VIM Conque-Term
vim 'https://conque.googlecode.com/files/conque_2.3.vmb' -c ':so % | q'
