#!/usr/bin/env bash

declare -a exclusion=(install original)

#git clone --recursive git://github.com/cello1500/dotfiles.git
#git submodule update --init --recursive "${DOTBOT_DIR}"

in_array() {
    local haystack=${1}[@]
    local needle=${2}
    for i in ${!haystack}; do
        if [[ ${i} == ${needle} ]]; then
            return 0
        fi
    done
    return 1
}

shopt -s nullglob

for f in ~/.dotfiles/*
do
	filename=${f##*/}
	if in_array exclusion $filename; then
		continue
	fi
	if [ -e ~/.$filename ] && [ ! -L ~/.$filename ]; then
		mkdir -p ~/.dotfiles/original
		mv ~/.$filename ~/.dotfiles/original_backup/
	fi

	ln -fsv $f ~/.$filename
done

# Install latest VIM Pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# install lastest VIM Syntastic
cd ~/.vim/bundle
git clone https://github.com/scrooloose/syntastic.git

# Install lastest VIM Sensible
cd ~/.vim/bundle
git clone git://github.com/tpope/vim-sensible.git

# Install VIM Conque-Term
vim 'https://conque.googlecode.com/files/conque_2.3.vmb' -c ':so % | q'

# Configure GO development environment
mkdir -p /code/go/src
mkdir -p /code/go/bin
mkdir -p /code/go3rd/bin
