#!/usr/bin/env bash

# Install VIM and needed utils
#sudo pacman -S --needed --noconfirm vim python-pip ctags yamllint

# Some neovim plugins need the nightly version
echo "[1/4] Installing neovim nightly"
yay -S neovim-nightly-bin

# Needed for telescope lua integration
echo "[2/4] Installing telescope dependencies"
yay -S fd ripgrep

echo "[3/4] Installing neovim symlinks"
yay -S neovim-symlinks

# Link from init file from dotfiles
echo "[4/4] Creating link from dotfiles to neovim init file"
ln -s ~/.dotfiles/init.vim ~/.config/nvim/init.vim

# Link from plugins directory from dotfiles
echo "[4/4] Creating link from dotfiles to neovim plugins directory"
ln -s ~/.dotfiles/plugin ~/.config/nvim/plugin

## Copy yamllint config files
#if [ -f "$HOME/.config/yamllint" ]; then
#  mv ~/.config/yamllint ~/.dotfiles/original_backup/yamllint
#fi
#ln -s ~/.dotfiles/yamllint ~/.config/yamllint
#exit 0
