- name: Install desktop management tools
  become: true
  package:
    name:
      - "{{ item }}"
    state: present
  with_items: "{{ desktop_packages }}"
  tags:
    - desktop

- name: Set up xinitrc
  lineinfile:
    dest: ~/.xinitrc
    state: present
    create: true
    insertafter: EOF
    regexp: "^exec .*"
    line: "exec i3"
    mode: '0644'
  tags:
    - desktop
