- name: Install desktop management tools
  become: yes
  package:
    name:
    - i3-wm
    - i3status
    - i3lock-color
    - scrot
    - xorg-server
    - arandr
    - picom
    - lxappearance
    - pcmanfm
    - feh
    - imagemagick
    - thunar
    - pacman-contrib
    - ttf-dejavu
    - ttf-liberation
    - noto-fonts
    - lightdm
    - lightdm-gtk-greeter
    - lightdm-gtk-greeter-settings
    - materia-gtk-theme
    - papirus-icon-theme
    state: present

- name: Set up xinitrc
  lineinfile:
    dest: ~/.xinitrc
    state: present
    create: yes
    insertafter: EOF
    regexp: "^exec .*"
    line: "exec i3"

- name: Fix audio issues sink
  become: yes
  lineinfile:
    dest: /etc/pulse/system.pa
    state: present
    create: yes
    insertafter: EOF
    regexp: "^load-module modulese-alsa.*"
    line: "load-module module-alsa-sink device=hw:0,0 channels=4"

- name: Fix audio issues  source
  become: yes
  lineinfile:
    dest: /etc/pulse/system.pa
    state: present
    create: yes
    insertafter: EOF
    regexp: "^load-module modulese-alsa.*"
    line: "load-module module-alsa-source device=hw:0,6 channels=4"

- name: Fix bluetooth issues policy
  become: yes
  lineinfile:
    dest: /etc/pulse/system.pa
    state: present
    create: yes
    insertafter: EOF
    regexp: "^load-module modules-bluetooth-policy$"
    line: "load-module module-bluetooth-policy"

- name: Fix bluetooth issues discover
  become: yes
  lineinfile:
    dest: /etc/pulse/system.pa
    state: present
    create: yes
    insertafter: EOF
    regexp: "^load-module modules-bluetooth-discover$"
    line: "load-module module-bluetooth-discover"
