- name: Install VM tooling on Linux
  become: true
  package:
    name:
      - virtualbox
      - virtualbox-host-modules-arch
      - virtualbox-guest-iso
      - virtualbox-ext-oracle
      - vagrant
    state: present
