- name: Installing stow
  package:
    name:
      - "{{ item }}"
    state: present
  with_items: "{{ dotfiles_packages }}"
  tags:
    - dotfiles

- name: Creating symlinks for configs
  shell: |
    pushd {{ lookup('env', 'HOME') }}/.dotfiles/configs
    stow -R -t {{ lookup('env', 'HOME') }} {{ item }}
  register: myoutput
  changed_when: myoutput.rc != 0
  with_items: "{{ config_dirs }}"
  tags:
    - dotfiles

- name: Creating symlinks for custom scripts
  become: true
  shell: |
    pushd {{ lookup('env', 'HOME') }}/.dotfiles/configs
    stow -R -t /usr/local/bin/ {{ item }}
  register: myoutput
  changed_when: myoutput.rc != 0
  with_items: "{{ script_dirs }}"
  tags:
    - dotfiles
