require('config.colorscheme')
require('config.completion')
require('config.fugitive')
require('config.lsp')
require('config.mappings')
require('config.netrw')
require('config.rego')
require('config.settings')
