- name: Fix bluetooth issues policy
  become: true
  lineinfile:
    dest: /etc/pulse/system.pa
    state: present
    create: true
    mode: '0644'
    insertafter: EOF
    regexp: "^load-module modules-bluetooth-policy$"
    line: "load-module module-bluetooth-policy"

- name: Fix bluetooth issues discover
  become: true
  lineinfile:
    dest: /etc/pulse/system.pa
    state: present
    create: true
    insertafter: EOF
    regexp: "^load-module modules-bluetooth-discover$"
    line: "load-module module-bluetooth-discover"
    mode: '0644'
