- name: Install pre-commit framework
  pip:
    name: pre-commit
  tags:
    - pre-commit

- name: Install checkov
  pip:
    name: checkov
  tags:
    - pre-commit

- name: Install terraform-docs
  command: "go install github.com/terraform-docs/terraform-docs@{{ terraform_docs_version }}"
  register: install_output
  changed_when: install_output.rc != 0
  tags:
    - pre-commit

- name: Install tflint
  command: "go install github.com/terraform-linters/tflint@{{ tflint_version }}"
  register: install_output
  changed_when: install_output.rc != 0
  tags:
    - pre-commit

- name: Install tfsec
  command: "go install github.com/aquasecurity/tfsec/cmd/tfsec@{{ tfsec_version }}"
  register: install_output
  changed_when: install_output.rc != 0
  tags:
    - pre-commit
