- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - ssh

- name: Install ssh private/public keys
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - {src: '{{ src_key }}', dest: '{{ dest_key }}', mode: '0600'}
    - {src: '{{ src_key }}.pub', dest: '{{ dest_key }}.pub', mode: '0644'}
  tags:
    - ssh

- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  tags:
    - ssh
