- name: Clone asdf
  become: true
  git:
    repo: https://github.com/asdf-vm/asdf.git
    version: "{{ asdf_version }}"
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    clone: true
    update: true
  tags:
    - asdf

- name: Sourcing asdf
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: present
    line: ". $HOME/.asdf/asdf.sh"
  tags:
    - asdf
