- name: Install nodejs tooling
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ nodejs_packages }}"
  tags:
    - nodejs

- name: Install gimme
  become: true
  get_url:
    url: https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
    dest: /usr/local/bin/gimme
    mode: 'u+x,g+x'
    group: users
  tags:
    - go

- name: Install direnv
  become: true
  get_url:
    url: https://github.com/direnv/direnv/releases/download/{{ direnv_version }}/direnv.linux-amd64
    dest: /usr/local/bin/direnv
    mode: 'u+x,g+x'
    group: users
  tags:
    - go
