- name: Install nodejs tooling
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ nodejs_packages }}"
  tags:
    - nodejs

- name: Install Rust tooling
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ rust_packages }}"
  tags:
    - rust

- name: Install Go tooling
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ go_packages }}"
  tags:
    - go

- name: Install direnv
  become: true
  get_url:
    url: https://github.com/direnv/direnv/releases/download/{{ direnv_version }}/direnv.linux-amd64
    dest: /usr/local/bin/direnv
    mode: 'u+x,g+x'
    group: users
  tags:
    - go

- name: Remove dagger
  file:
    state: absent
    path: "{{ lookup('env', 'HOME') }}/opt/dagger"
  tags:
    - dagger

- name: Clone dagger
  git:
    repo: 'https://github.com/dagger/dagger.git'
    dest: "{{ lookup('env', 'HOME') }}/opt/dagger"
  tags:
    - dagger

- name: Build dagger
  shell: "cd {{ lookup('env', 'HOME') }}/opt/dagger && make dagger"
  register: build_output
  changed_when: build_output.rc != 0
  tags:
    - dagger

- name: Install dagger
  become: true
  copy:
    src: "{{ lookup('env', 'HOME') }}/opt/dagger/cmd/dagger/dagger"
    dest: /usr/local/bin/dagger
    mode: 'u+x,g+x'
    group: users
  tags:
    - dagger

- name: Enable dagger autocompletion for zsh
  become: true
  shell: 'dagger completion zsh > "${fpath[1]}/_dagger"'
  register: build_output
  changed_when: build_output.rc != 0
  tags:
    - dagger
