- name: Install kubectl
  become: true
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 'u+x,g+x'
    group: users
  tags:
    - kubectl

- name: Enable kubectl auto-completion bash
  become: true
  lineinfile:
    dest: "~aristides/.bashrc"
    state: present
    create: true
    mode: '0644'
    insertafter: EOF
    regexp: "kubectl"
    line: "source <(kubectl completion bash)"
  tags:
    - kubectl

- name: Install OPA client
  become: true
  get_url:
    url: https://openpolicyagent.org/downloads/{{ opa_version }}/opa_linux_amd64
    dest: /usr/local/bin/opa
    mode: 'u+x,g+x'
    group: users
  tags:
    - opa

- name: Install kind
  become: true
  get_url:
    url: https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64
    dest: /usr/local/bin/kind
    mode: 'u+x,g+x'
    group: users
  tags:
    - kind

# - name: Install operator-sdk
#   shell: echo "Install operator-sdk"
