- name: Install kubectl
  become: true
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 'u+x,g+x'
    group: users
  tags:
    - kubectl

- name: Enable kubectl auto-completion bash
  become: true
  lineinfile:
    dest: "~aristides/.bashrc"
    state: present
    create: true
    mode: '0644'
    insertafter: EOF
    regexp: "kubectl"
    line: "source <(kubectl completion bash)"
  tags:
    - kubectl

- name: Install crictl
  become: true
  get_url:
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl_version }}/crictl-{{ crictl_version }}-linux-amd64.tar.gz
    dest: /tmp/crictl-{{ crictl_version }}-linux-amd64.tar.gz
    mode: 'u+x,g+x'
    group: users
    checksum: sha512:f8c40c66c8d9a85e857399506f4977564890815b02658eec591114e04bd8bc6b8ea08bcc159af0088b5eda7bf0dfd16096bf0c174819c204193fb7343ae7d9d5
  tags:
    - crictl

- name: Unarchive crictl
  become: true
  unarchive:
    src: /tmp/crictl-{{ crictl_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin
  tags:
    - crictl

- name: Install OPA client
  become: true
  get_url:
    url: https://openpolicyagent.org/downloads/{{ opa_version }}/opa_linux_amd64
    dest: /usr/local/bin/opa
    mode: 'u+x,g+x'
    group: users
  tags:
    - opa

- name: Install kind
  become: true
  get_url:
    url: https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64
    dest: /usr/local/bin/kind
    mode: 'u+x,g+x'
    group: users
  tags:
    - kind

- name: Clone Operator-SDK
  git:
    repo: 'https://github.com/operator-framework/operator-sdk'
    dest: "{{ lookup('env', 'HOME') }}/opt/operator-sdk"
  tags:
    - operator-sdk

- name: Build Operator-SDK
  shell: |
    cd {{ lookup('env', 'HOME') }}/opt/operator-sdk
    git checkout master
    make install
  register: build_output
  changed_when: build_output.rc != 0
  tags:
    - operator-sdk
