- name: Check Terraform version
  shell: "terraform --version | head -n1 | grep {{ terraform_version }}"
  failed_when: False
  changed_when: False
  register: current_terraform_version

- name: Determine Terraform checksums
  uri: url="https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_SHA256SUMS"
       method="GET"
       return_content=True
  register: terraform_checksums

- name: Download Terraform
  become: yes
  get_url: url="https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
           dest="/usr/local/src/terraform_{{ terraform_version }}_linux_amd64.zip"
           checksum="sha256:{{ item.split(' ') | first }}"
  with_items: "{{ terraform_checksums.content.split('\n') | select('search', 'linux_amd64') | list | first }}"
  register: terraform_downloaded

- name: Extract and install Terraform
  become: yes
  unarchive: src="/usr/local/src/terraform_{{ terraform_version }}_linux_amd64.zip"
             dest=/usr/local/bin
             copy=no
  when: current_terraform_version.rc != 0 or terraform_downloaded | changed

- name: Enable terraform auto-completion
  shell: terraform -install-autocomplete
