- name: Install cfssl
  become: true
  get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v{{ cfssl_version }}/{{ item }}_{{ cfssl_version }}_linux_amd64
    dest: /usr/local/bin/{{ item }}
    mode: 'u+x,g+x'
  with_items:
    - '{{ cfssl_packages }}'
  tags:
    - ssl
