- name: Install media tooling on Linux
  become: true
  package:
    name:
      - "{{ item }}"
    state: present
  with_items: "{{ media_packages }}"
  tags:
    - media

- name: Fix audio issues sink
  become: true
  lineinfile:
    dest: /etc/pulse/system.pa
    state: present
    create: true
    mode: '0644'
    insertafter: EOF
    regexp: "^load-module modulese-alsa.*"
    line: "load-module module-alsa-sink device=hw:0,0 channels=4"
  tags:
    - media

- name: Fix audio issues  source
  become: true
  lineinfile:
    dest: /etc/pulse/system.pa
    state: present
    create: true
    mode: '0644'
    insertafter: EOF
    regexp: "^load-module modulese-alsa.*"
    line: "load-module module-alsa-source device=hw:0,6 channels=4"
  tags:
    - media
