- name: Install docker tooling on Linux
  become: true
  package:
    name:
      - docker
    state: present
  tags:
    - docker

- name: Add user to the group docker
  user:
    name: aristides
    groups:
      - docker
    append: true
  tags:
    - docker

- name: Make sure a docker service unit is running
  systemd:
    state: started
    name: docker
  tags:
    - docker

- name: Install docker-compose
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
  tags:
    - docker

- name: Clone dive package
  become: true
  git:
    repo: https://aur.archlinux.org/dive.git
    dest: /home/aristides/opt
    clone: true
    update: true
  tags:
    - docker

- name: Build dive from source
  command: "makepkg -csi --noconfirm"
  register: myoutput
  changed_when: myoutput.rc != 0
  args:
    chdir: /home/aristides/opt
  tags:
    - docker
