- name: Install docker tooling on Linux
  become: yes
  package:
    name:
    - docker
    state: present

- name: Add user to the group docker
  user:
    name: aristides
    groups: docker
    append: yes

- name: Make sure a docker service unit is running
  systemd:
    state: started
    name: docker

- name: Install docker-compose
  become: yes
  get_url:
    url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
