- name: Full system upgrade
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: Install base linux requirements
  become: true
  package:
    name:
      - base-devel
      - curl
      - dos2unix
      - flameshot
      - git
      - htop
      - jq
      - lsof
      - ncdu
      - rsync
      - stow
      - tree
      - wget
    state: present
