- name: Install base linux requirements
  become: true
  package:
    name:
      - base-devel
      - curl
      - dos2unix
      - flameshot
      - git
      - htop
      - jq
      - lsof
      - ncdu
      - rsync
      - stow
      - tree
      - wget
    state: present
  tags:
    - base
