- name: Full system upgrade
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install base linux requirements
  become: yes
  package:
    name:
    - flameshot
    - git
    - htop
    - jq
    - lsof
    - ncdu
    - rsync
    - stow
    - tree
    - wget
    state: present
