- name: Install Alacritty on Linux
  become: true
  package:
    name:
      - cmake
      - freetype2
      - fontconfig
      - pkg-config
      - make
      - libxcb
      - alacritty
    state: present
