- name: Install Neovim on Linux
  become: true
  package:
    name:
      - neovim-nightly-bin
      - neovim-symlinks
      - python-pynvim
      - fd
      - ripgrep
      - fzf
      - python-pip
    state: present

- name: Install python-pynvim
  pip:
    name: neovim
    extra_args: --user --upgrade
